spring.application.name=demo
coderslab.custom.property=my custom value
spring.datasource.generate-unique-name=false


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# MySQL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:5066/bookStore?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=RqUF3zPGvCVj!I3c
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:coderslab
#spring.datasource.username=root
#spring.datasource.password=coderslab

