spring.application.name=demo
coderslab.custom.property=my custom value
spring.datasource.generate-unique-name=false

spring.datasource.url=jdbc:h2:mem:coderslab
spring.datasource.username=root
spring.datasource.password=coderslab

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

